from typing import Protocol

from src.domain.vpn.entities import VPNNode, VPNNodeID, VPNClient, VPNSession


class IVPNNodeRepository(Protocol):
    async def add(self, node: VPNNode) -> VPNNode: ...

    async def get_by_id(self, node_id: VPNNodeID) -> VPNNode | None: ...

    async def list(self, limit: int = 100, offset: int = 0) -> list[VPNNode]: ...

    async def delete(self, node_id: VPNNodeID) -> None: ...


class IVPNClientRepository(Protocol):
    async def add(self, client: VPNClient) -> VPNClient: ...

    async def list(self, node_id: int) -> list[VPNClient]: ...

    async def revoke(self, client_name: str, node_id: int) -> None: ...


class IVPNSessionRepository(Protocol):
    async def add(self, session: VPNSession, node_id: int) -> VPNSession: ...

    async def list(self, node_id: int) -> list[VPNSession]: ...

    async def clear_node_sessions(self, node_id: int) -> None: ...
