services:
  openvpn-agent:
    build: .
    container_name: openvpn-agent
    volumes:
      - ${HOME}/openvpn-utils/openvpn-data/server:/etc/openvpn/server
      - ${HOME}/openvpn-utils/openvpn-data/home:/root/openvpn/
      - ${HOME}/openvpn-utils/scripts:/root/openvpn/scripts
    environment:
      - SCRIPTS_DIR=/root/openvpn/scripts
      - CLIENT_CONFIG_DIR=/root/openvpn/clients-configs/files
      - MGMT_PORT=55555
      - MGMT_ADDRESS=127.0.0.1
    network_mode: host