services:
  openvpn-agent:
    build: .
    container_name: openvpn-agent
    volumes:
      - ${HOME}/openvpn-utils/openvpn-data/server:/etc/openvpn/server
      - ${HOME}/openvpn-utils/openvpn-data/home:/root/openvpn/
      - ${HOME}/openvpn-utils/scripts:/root/openvpn/scripts
    environment:
      - SCRIPTS_DIR=/root/openvpn/scripts
      - MGMT_PORT=55555
      - MGMT_ADDRESS=host.docker.internal
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"